#!/usr/bin/make

# This file contains the substitution-rules for "sed"

# Space-separated list of all "raw" php-/perl-files.
PHP_FILES_UNCONF=	mmimport mmexport rezept2latex rk2mm

SUBDIRS=		""

CONF_FILE=		../config.sed

all: build
	@#make subdir TRGT=all

build: ${PHP_FILES_UNCONF}

${PHP_FILES_UNCONF}: ${PHP_FILES_UNCONF:C,$,.raw,}
	sed -f ${CONF_FILE} ${@}.raw > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$$i";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}";\
	done )

clean:
	@#make subdir TRGT=clean
	rm -f ${PHP_FILES_UNCONF}

distclean:

install:
	( [ -d "<%%SCRIPT_PREFIX%%>" ] || \
	install -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> <%%SCRIPT_PREFIX%%> )
	@( for i in ${PHP_FILES_UNCONF} ; do \
	install -c -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> $$i <%%SCRIPT_PREFIX%%>; \
	echo "install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> $$i <%%SCRIPT_PREFIX%%>" ; \
	done )

.PHONY: all subdir clean distclean install 
