#!/usr/bin/make

# This file contains the substitution-rules for "sed"

# Space-separated list of all "raw" php-/perl-files.
PHP_FILES=		mmimport rezept rk2mm

SUBDIRS=		""

CONF_FILE=		../config.sed

all: build
	@#make subdir TRGT=all

build: ${PHP_FILES}

${PHP_FILES}: ${PHP_FILES:%=%.raw}
	sed -f ${CONF_FILE} ${@}.raw > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$$i";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}";\
	done )

clean:
	@#make subdir TRGT=clean
	rm -f ${PHP_FILES}

distclean:

install: build
	( [ -d "<%%SCRIPT_PREFIX%%>" ] || \
	install -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> <%%SCRIPT_PREFIX%%> )
	install -c -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${PHP_FILES} <%%SCRIPT_PREFIX%%>

.PHONY: all subdir clean distclean install
