# Space-separated list of all "raw" php-files.

# Files to install unmangled (dont forget the filename-suffix here!)
PICS=			blue_dot.gif help_dot.gif info_dot.gif title.gif \
			left.gif lupe.gif right.gif walking.gif white.gif \
			write.gif ok.gif
SUBDIRS=		

CONF_FILE=		../../config.sed

all:
	@#${MAKE} subdir TRGT=all

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$$i";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}";\
	cd ..; \
	done )

clean:
	@#${MAKE} subdir TRGT=clean

distclean:

install:
	( [ -d "${DESTDIR}/<%%WEB_PREFIX%%>/pics" ] || \
	<%%INSTALL%%> -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%WEB_PREFIX%%>/pics )
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${PICS} ${DESTDIR}/<%%WEB_PREFIX%%>/pics ; \
