# Space-separated list of all "raw" php-files.

# Files to install unmangled (dont forget the filename-suffix here!)
PICS=			title.gif blue_dot.gif white.gif
SUBDIRS=		

CONF_FILE=		../../config.sed

all:
	@#make subdir TRGT=all

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$$i";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}";\
	cd ..; \
	done )

clean:
	@#make subdir TRGT=clean

distclean:

install:
	( [ -d "${DESTDIR}/<%%WEB_PREFIX%%>/pics" ] || \
	install -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%WEB_PREFIX%%>/pics )
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${PICS} ${DESTDIR}/<%%WEB_PREFIX%%>/pics ; \
