# $Id: Makefile.raw,v 1.12 2002/08/10 22:23:11 lestinsky Exp $
# Space-separated list of all "raw" php-files.

CONF_FILE=	../config.sed

SUBDIRS=	man1

all:
	@${MAKE} subdir TRGT=all

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$${i}";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}/$${i}";\
	cd ..; \
	done )

install:
	@${MAKE} subdir TRGT=install DESTDIR=${DESTDIR}

clean:
	@${MAKE} subdir TRGT=clean

distclean:
	@${MAKE} subdir TRGT=distclean
	@( for i in ${SUBDIRS}; do \
	echo "rm -f $${i}/Makefile" ; \
	rm -f $${i}/Makefile; \
	done)

.PHONY: man1 all subdir clean distclean install
