# $Id: Makefile.raw,v 1.10 2001/10/01 00:02:41 lestinsky Exp $
# Space-separated list of all "raw" php-files.

MAN1=	mmimport.1 rezept.1
MAN=	${MAN1}

CONF_FILE=	../config.sed

all: man

man: man1

man1:
	@(cd man1; for i in ${MAN1}; do\
	echo "$$i.raw --> $$i" ;\
	sed -f ../${CONF_FILE} $$i.raw > $$i;\
	done)

clean:
	(cd man1; rm -rf ${MAN1})

distclean:

install-man1:
	@( test -d "${DESTDIR}/<%%MAN_PREFIX%%>/man1" || \
	install -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%MAN_PREFIX%%>/man1 )
	@(cd man1; for i in ${MAN1}; do \
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> $$i ${DESTDIR}/<%%MAN_PREFIX%%>/man1;\
	echo "install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> $$i ${DESTDIR}/<%%MAN_PREFIX%%>/man1";\
	done)

install: man install-man1

.PHONY: man1 all subdir clean distclean install
