# $Id: Makefile.raw,v 1.16 2001/02/16 09:48:37 michael Exp $
# Space-separated list of all "raw" php-files.
PHP_FILES=		delete.php einfuegen.php index.php infos.php \
			rezept.php print.php mmprint.php kategorien.php
INC_FILES=		menue.inc such.inc

# Files to install unmangled (dont forget the filename-suffix here!)
ADDITIONAL=		styles.css
SUBDIRS=		pics

CONF_FILE=		../config.sed

all: build
	@make subdir TRGT=all

build: ${PHP_FILES} ${INC_FILES}

${PHP_FILES}: ${PHP_FILES:%.php=%.raw}
	sed -f ${CONF_FILE} ${@:%.php=%.raw} > ${@}

${INC_FILES}: ${INC_FILES:%.inc=%.raw}
	sed -f ${CONF_FILE} ${@:%.inc=%.raw} > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$${i}";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}/$${i}";\
	cd ..; \
	done )

clean:
	@make subdir TRGT=clean
	rm -f ${PHP_FILES} ${INC_FILES}

distclean:
	@make subdir TRGT=distclean
	@( for i in ${SUBDIRS}; do \
	echo "rm -f $${i}/Makefile" ; \
	rm -f $${i}/Makefile; \
	done)

install: build
	@make subdir TRGT=install
	@( test -d "<%%WEB_PREFIX%%>" || \
	install -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> <%%WEB_PREFIX%%> )
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${PHP_FILES} <%%WEB_PREFIX%%>
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${INC_FILES} <%%WEB_PREFIX%%>
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${ADDITIONAL} <%%WEB_PREFIX%%>

.PHONY: all subdir clean distclean install
