# $Id: Makefile.raw,v 1.20 2001/05/08 19:51:13 michael Exp $
# Space-separated list of all "raw" php-files.
PHP_FILES=		delete.php einfuegen.php index.php infos.php \
			rezept.php print.php mmprint.php kategorien.php \
			help.php units.php
INC_FILES=		menue.inc such.inc

# Files to install unmangled (dont forget the filename-suffix here!)
ADDITIONAL=		styles.css ../LICENSE
SUBDIRS=		pics

CONF_FILE=		../config.sed

all: build
	@make subdir TRGT=all

build: ${PHP_FILES} ${INC_FILES}

${PHP_FILES}: ${PHP_FILES:%.php=%.raw}
	sed -f ${CONF_FILE} ${@:%.php=%.raw} > ${@}

${INC_FILES}: ${INC_FILES:%.inc=%.raw}
	sed -f ${CONF_FILE} ${@:%.inc=%.raw} > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$${i}";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}/$${i}";\
	cd ..; \
	done )

clean:
	@make subdir TRGT=clean
	rm -f ${PHP_FILES} ${INC_FILES}

distclean:
	@make subdir TRGT=distclean
	@( for i in ${SUBDIRS}; do \
	echo "rm -f $${i}/Makefile" ; \
	rm -f $${i}/Makefile; \
	done)

install: build
	@make subdir TRGT=install DESTDIR=${DESTDIR}
	@( test -d "${DESTDIR}/<%%WEB_PREFIX%%>" || \
	install -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%WEB_PREFIX%%> )
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${PHP_FILES} ${DESTDIR}/<%%WEB_PREFIX%%>
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${INC_FILES} ${DESTDIR}/<%%WEB_PREFIX%%>
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${ADDITIONAL} ${DESTDIR}/<%%WEB_PREFIX%%>

.PHONY: all subdir clean distclean install
