<!-- Links: Programm-Menue -->
<table border=0 cellspacing=0 cellpadding=1>
  <tr style="background-color:#b0b0b0;" align="top">
    <td>
      <table border="0" cellspacing="0" cellpadding="3">
        <tr>
          <td style="background-color:#f0f0f0">
            <img src="pics/white.gif" align="top" alt=""><a href="<? echo $PHP_SELF . "?suchen=1" ?>">Suchen</a><br>
            <img src="pics/white.gif" align="top" alt=""><a href="">Einf&uuml;gen</a></br>
                <img src="pics/white.gif" align="top" alt=""><a href="">Infos</a></br>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>

