# $Id: Makefile.raw,v 1.3 2008/11/29 01:34:58 lestinsky Exp $
# Space-separated list of all "raw" php-files.

MAN1=	mmimport.1 rezept.1

CONF_FILE=	../../config.sed

SUBDIRS=

all: build
	@${MAKE} subdir TRGT=all

build: ${MAN1}

${MAN1}: ${MAN1:%=%.raw} ${CONF_FILE}
	sed -f ${CONF_FILE} ${@:%=%.raw} > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do \
	echo "====> ${THISDIR}/$${i}"; \
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}/$${i}"; \
	cd ..; \
	done )

clean:
	@${MAKE} subdir TRGT=clean
	rm -f ${MAN1}

distclean:
	@${MAKE} subdir TRGT=distclean
	@( for i in ${SUBDIRS}; do \
	echo "rm -f $${i}/Makefile" ; \
	rm -f $${i}/Makefile; \
	done)

install: build
	@${MAKE} subdir TRGT=install DESTDIR=${DESTDIR}
	@( test -d "${DESTDIR}/<%%MAN_PREFIX%%>" || \
	<%%INSTALL%%> -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%MAN_PREFIX%%>/man1 )
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${MAN1} ${DESTDIR}/<%%MAN_PREFIX%%>/man1


.PHONY: man1 all subdir clean distclean install
