#!/usr/local/bin/php -q
<?

  /*
   * $Id: mmimport,v 1.1 2000/10/26 01:20:25 michael Exp $
   * Michael Lestinsky <michael@zaphod.rhein-neckar.de>, Okt. 2000
   * Import mealmaster-formated recipes to the "Koch-Suite".
   *
   * Please see the bundled file "LICENCE" for the licence of this
   * script.
   */

  require "./include/functions.inc";


  /* --- Main --- */

  while ($line = fgets($stdin, 1024)) {

    /* Is the line the start of a new recipe? */
    if (ereg("(-{5}|M{5}).*Meal-Master.*", $line)) { 
      /* parse the recipe */
      $rezept = parse_mmrecipe($stdin);
      fputs($stdout, format_recipe($rezept));
    }
  }

  /* --- End --- */
?>
