#!/usr/local/bin/php -q
<?

  /*
   * $Id: mmimport,v 1.2 2000/11/01 12:54:18 michael Exp $
   * Michael Lestinsky <michael@zaphod.rhein-neckar.de>, Okt. 2000
   * Import mealmaster-formated recipes to the "Koch-Suite".
   *
   * Please see the bundled file "LICENCE" for the licence of this
   * script.
   */

  require "./include/functions.inc";

  /* Create a temporary file, write $stdin to it and close the
   * temporary file. 
   * Why this way instead of using /dev/stdin directly:
   *   fseek doesn't work on /dev/stdin.
   */

  $temp = tempnam("/tmp", "mmimport");

  echo "$temp\n";
  $temp_fd = fopen($temp, "w");

  while ($line = fgets($stdin, 1024)) {
    fputs ($temp_fd, $line);
  }
  fclose ($temp_fd);

  /* Reopen the temporary file for reading */

  $fd = fopen($temp, "r");

  /* --- Main --- */

  while ($line = fgets($fd, 1024)) {
    /* Is the line the start of a new recipe? */
    if (ereg("(-{5}|M{5}).*Meal-Master.*", $line)) { 
      /* parse the recipe */
      $rezept = parse_mmrecipe($fd);
      fputs($stdout, format_recipe($rezept));
    }
  }

  /* Close open files */

  fclose($fd);

  /* --- End --- */
?>
