<?php
  /*
   * $Id: es.inc,v 1.10 2003/08/11 20:11:32 lestinsky Exp $
   *
   * Define Spanish text-constants.
   *
   * This file is subject to the license as included in ../LICENSE
   * (c) 2002 Michael Lestinsky
   */

  /* Menu */
  $Lang['Insert']		= "Insertar";
  $Lang['Help']			= "Ayuda";
  $Lang['Info']			= "Informaci&oacute;n";

  $Lang['Title']		= "T&iacute;tulo";
  $Lang['Yield']		= "Porciones";
  $Lang['Cat'] 			= "Categor&iacute;as";
  $Lang['Ingred']		= "Ingredientes";
  $Lang['Units']		= "Unidades";
  $Lang['Preparation']		= "Preparaci&oacute;n";
  $Lang['Text']			= "Texto";
  $Lang['Description']		= "Descripci&oacute;n";
  $Lang['Alias']		= "Alias";
  $Lang['Recorder']		= "Registrada por";
  $Lang['Date']			= 'Dia';
  $Lang['Source']		= 'Fuente';
  $Lang['Instructions']		= 'Instruciones';
  $Lang['Rating']		= 'Puntuaci&oacute;n';
  $Lang['Vote']['Submit']	= 'Puntua esta receta';
  $Lang['Contact']		= 'Contacto';
  $Lang['TotalRecipes']		= 'N&uacute;mero total de recetas';

  $Lang['FormApply']		= "Aplicar";
  $Lang['FormMoreIngr']		= "Ingredientes adicionales";
  $Lang['FormReset']		= "Borrar formulario";

  $Lang['Delete']		= "Borrar";
  $Lang['NormalVers']		= "Vista normal";
  $Lang['PrintVers']		= "Versi&oacute;n imprimible";
  $Lang['Close']		= "Cerrar";
  $Lang['Edit']                 = "Editar";
  $Lang['Next']			= "Siguiente";
  $Lang['Previous']		= "Anterior";
  $Lang['LastResult']		= '&Uacute;ltimo resultado';
  $Lang['Apply']		= 'Aplicar';
  $Lang['Tag']['Do']		= 'Marcar';
  $Lang['Tag']['All']		= 'Marcar todas';
  $Lang['Tag']['Show']['Do']	= 'Mostrar recetas marcadas';
  $Lang['Tag']['Show']['Title']	= 'Recetas marcadas';
  $Lang['Untag']['Do']		= 'Desmarcar';
  $Lang['Untag']['All']		= 'Desmarcar todas';

  $Lang['Mainmenu']['Title']		= "Men&uacute; principal";
  $Lang['Mainmenu']['PlsChoose']	= "Por favor seleccione del men&uacute; principal";
  $Lang['Search']['Search']	= "Buscar";
  $Lang['Search']['For']	= "Buscar";
  $Lang['Search']['In']		= "Buscar en";
  $Lang['Search']['Go']		= "Comenzar busqueda";
  $Lang['Search']['Result']	= "Resultados de la busqueda";
  $Lang['Search']['Hits']       = "Resultados";

  $Lang['Search']['Menutitle']	= "T&iacute;tulo del men&uacute;";
  $Lang['Search']['Categories']	= "Categor&iacute;as";
  $Lang['Search']['Ingredients']	= "Ingredientes";
  $Lang['Search']['NoResult']	= "No se obtuvieron resultados.";

  $Lang['Recipe']['Edit']	= "Editar receta";
  $Lang['Recipe']['Delete']	= "Borrar receta";
  $Lang['Recipe']['Deleted']    = "Receta borrada";
  $Lang['Recipe']['Insert']     = "Insertar receta en la base de datos";
  $Lang['Recipe']['Inserted']   = "Receta insertada.";

  $Lang['Auth']['Login']	= 'Entrar';
  $Lang['Auth']['LoggedInAs']   = 'Conectado como';
  $Lang['Auth']['Logout']       = 'Salir';
  $Lang['Auth']['NoLogin']      = 'No conectado';
  $Lang['Auth']['AccessDenied'] = 'Lo siento, no tiene acceso a esta funcionalidad.';
  $Lang['Auth']['AccountLocked']	= 'Su cuenta ha sido deshabilitada.';

  $Lang['Admin']['Title']	= 'Administraci&oacute;n';
  $Lang['Admin']['NewUser']['Title']    = 'Crear un nuevo usuario';
  $Lang['Admin']['NewUser']['Username'] = 'Nombre de usuario';
  $Lang['Admin']['NewUser']['Realname'] = 'Nombre real';
  $Lang['Admin']['NewUser']['EMail']    = 'Cuanta de correo electr&oacute;nico';
  $Lang['Admin']['NewUser']['Usertype'] = 'Tipo de Usuario';
  $Lang['Admin']['ErrMsg']['EmptyFields']       = 'Por favor rellene todos los campos.';
  $Lang['Admin']['ErrMsg']['InvalidMail']       = 'La direcci&oacute;n de correo es incorrecta.';
  $Lang['Admin']['ErrMsg']['UserExists']        = 'El nombre de usuario ya existe.';
  $Lang['Admin']['ErrMsg']['UserLocked']	= 'Esta cuenta ya estaba bloqueada.';
  $Lang['Admin']['ErrMsg']['UserDoesntExist']	= 'Este usuario es invalido/desconocido.';
  $Lang['Admin']['UserClass']['Read']	= 'Solo lectura';
  $Lang['Admin']['UserClass']['Write']	= 'Lectura/Escritura';
  $Lang['Admin']['UserClass']['Moderate']	= 'Moderador';
  $Lang['Admin']['UserClass']['Admin']	= 'Administrador';
  $Lang['Admin']['LockAccount']['Title']	= 'Bloquea una cuenta';
  $Lang['Admin']['LockAccount']['Username']	= 'Nombre de usuario';
  $Lang['Admin']['LockAccount']['Lock']	= 'Bloquea la cuenta';

  $Lang['Settings']['Title']	= "Tus preferencias";
  $Lang['Settings']['Password']['Title']	= "Cambia tu contrase&ntilde;a";
  $Lang['Settings']['Password']['Old']		= "Contrase&ntilde;a antigua";
  $Lang['Settings']['Password']['New']		= "Nueva contrase&ntilde;a";
  $Lang['Settings']['Password']['Retype']	= "Confirma la nueva contrase&ntilde;a";
  $Lang['Settings']['Password']['nomatch']	= "Las contrase&ntilde;as no coinciden.";
  $Lang['Settings']['Password']['changed']      = "Contrase&ntilde;a cambiada.";

  $Lang['Pastebox']['Title']            = 'Caja de pegado';
  $Lang['Pastebox']['Text']             = <<<EOT
     Pega abajo una receta &uacute;nica y preformateada en formato Meal-Master o RezKonv.
EOT;

  $Lang['AllRecipes']		= "Todas las recetas";
  $Lang['CatChoose']		= "Selector de categor&iacute;a";

  $Lang['Aliases']['DefDescr']  = "escriba la lista de aliases separada por espacios.";

  $Lang['Category']['Title']    = "Categor&iacute;as definidas";
  $Lang['Category']['Help']     = <<<EOT
      Por favor seleccione 5 diferentes categor&iacute;as como m&aacute;ximo. Haga click
      en la categor&iacute;a para insertar el valor en la forma.
EOT;
  $Lang['Category']['Edit']     = 'Editar Categor&iacute;as';
  $Lang['Category']['EditAlias']= 'Editar alias';
  $Lang['Category']['MakeAlias']= 'Haz un alias para';
  $Lang['Category']['Delete']   = 'Borrar categor&iacute;a';

  $Lang['UnitInfo']['Title']    = "Informaci&oacute;n de unidades";
  $Lang['UnitInfo']['MMText']   = "Unidades en formato Meal-Master.";
  $Lang['UnitInfo']['RKText']   = "Unidades en formato REZKONV.";

  $Lang['Scale']['Title']	= 'Cambiar las porciones';


  /*
   * Infos:
   */

  $Lang['Infos']['Title']        = "Informaci&oacute;n acerca de " . KOCHSUITE;

  $Lang['Homepage']['Title']	= 'P&aacute;gina de inicio';
  $Lang['Homepage']['Text'][0]	= <<<EOT
      <a href="http://koch-suite.berlios.de/">http://koch-suite.berlios.de/</a>:
      Informaci&oacute;n actualizada de &eacute;ste proyecto, y las m&aacute;s recientes
      versiones de 
EOT;
  $Lang['Homepage']['Text'][0] .= KOCHSUITE . " pueden ser encontradas aqu&iacute;.";

  $Lang['Version']['Title']             = 'Versi&oacute;n';
  $Lang['Version']['Text']['Pre']       = "Est&aacute; instalado " . KOCHSUITE;
  $Lang['Version']['Text']['Post']      = "";

  $Lang['Requirements']['Title']	= 'Requisitos';
  $Lang['Requirements']['Text'][0]	= 'Software requerido:';

  $Lang['Requirements']['Software'][0]	= '<a href="http://www.mysql.org">MySQL</a> (probado con la versi&oacute;n 3.23) o <A HREF="http://www.postgresql.org/">PostgreSQL</A> (probado con la versi&oacute;n 7.2.1)';
  $Lang['Requirements']['Software'][1]	= '<a href="http://www.php.net">PHP</a> (Versi&oacute;n 4.1 o mayor), con soporte para MySQL o PostgreSQL y un PEAR actual,';
  $Lang['Requirements']['Software'][2]	= 'un servidor Web soportado por PHP (p. ej. <a href="http://www.apache.org">Apache</a>)';

  $Lang['Requirements']['Text'][1]	= 'Probado en los siguientes sistemas operativos (en orden alfab&eacute;tico):';

//  $Lang['Requirements']['OSes'][0]	= 'AIX 4.3';
  $Lang['Requirements']['OSes'][1]	= 'FreeBSD';
  $Lang['Requirements']['OSes'][2]	= 'Linux (Debian 2.2, 3.0)';
  $Lang['Requirements']['OSes'][3]	= 'OpenBSD';
  $Lang['Requirements']['OSes'][4]	= 'Solaris 2.[5-9]';

  $Lang['Requirements']['Text'][2]	= <<<EOT
      Necesitar&aacute; tener PHP compilado con soporte para MySQL y PostgreSQL
      como un int&eacute;rprete independiente para utilizar las herramientas de
      l&iacute;nea de comando. Para la interfaz web necesitar&aacute; PHP instalado como
      CGI o como m&oacute;dulo de Apache.
EOT;

  $Lang['License']['Title']	= "Licencia";
  $Lang['License']['Pre'][0]	= "Todo el paquete " . KOCHSUITE . " es liberado en los t&eacute;rminos de la siguiente licencia estilo BSD.\n";
  $Lang['License']['Post'][0]	= "";


  /* 
   * Help:
   */

  $Lang['Helptext']['General']	= <<<EOT
    <p class="top">
      &Eacute;ste programa consiste en &eacute;stas tres partes principales:
      una gran biblioteca que contiene todas las funciones de conversi&oacute;n y salida,
      (wrappers m&aacute;s o menos triviales para &eacute;sta biblioteca), unas pocas
      herramientas de l&iacute;nea de comando y un frontend basado en web.
    <p>
EOT;

  $Lang['Language']['Title']	= "Opciones de idioma";
  $Lang['Language']['Text'][0]	= <<<EOT
      La Koch-Suite soporta varios idiomas desde la versión 0.5.
      Para seleccionar otro idioma, ajuste su browser (p. ej. Mozilla:
      Editar -> Preferencias -> Navegador -> Idiomas)
      Si el idioma que Ud. especific&oacute; existe, ver&aacute; todas las
      p&aacute;ginas siguientes en el idioma solicitado. De otra forma el idioma
      por defecto (Alem&aacute;n "de") ser&aacute; utilizado.
      Claro que no se traducir&aacute;n las recetas mismas. Esta selecci&oacute;n solamente
      influye en el idioma de la interfaz.
EOT;

  $Lang['Helptext']['CL']['Title']	= "Herramientas de l&iacute;nea de comandos";
  $Lang['Helptext']['CL']['commands'][0]['Name'] = "mmimport";
  $Lang['Helptext']['CL']['commands'][0]['Text'] = <<<EOT
          Importa recetas. La entrada se esperar&aacute; de la entrada estandar 
          (STDIN). 
          Las recetas ser&aacute;n extraidas del texto circundante, y pueden estar
          en formato Meal-Master &oacute; en formato
          <a href="http://home.t-online.de/home/ufetzer/">REZKONV</a>.
          Lea tambi&eacute;n <code>mmimport(1)</code>
EOT;
  $Lang['Helptext']['CL']['commands'][1]['Name'] = "rezept";
  $Lang['Helptext']['CL']['commands'][1]['Text'] = <<<EOT
          Busca recetas en la base de datos y las imprime como
          c&oacute;digo fuente de LaTeX, en formato Meal-Master, &oacute;
          como texto legible por humanos, a la salida est&aacute;ndar. 
          Lea <code>rezept(1)</code>.
EOT;

  $Lang['Helptext']['WWW']['Title']	= "Web Frontend";
  $Lang['Helptext']['WWW']['part'][0]['Title']	= "Interfaz de b&uacute;squeda";
  $Lang['Helptext']['WWW']['part'][0]['Text']	= <<<EOT
        Ud. puede buscar en la base de datos por t&eacute;rminos en
          <ul>
            <li>los t&iacute;tulos de los men&uacute;s</li>
            <li>las categor&iacute;as</li>
            <li>las listas de ingredientes</li>
          </ul>
        El resultado es una lista de todas las recetas que contienen el
        t&eacute;rmino especificado en el campo seleccionado.
        Seleccione "Buscar" en el men&uacute; principal, escriba el t&eacute;rmino en
        la forma, elija de "Buscar en" en donde se buscar&aacute; por el t&eacute;rmino
        y haga click en el bot&oacute;n "Iniciar b&uacute;squeda".
        A partir de la versi&oacute;n <i>0.5</i> Ud. puede combinar varios
        t&eacute;rminos usando la palabra "AND" (¡en may&uacute;sculas!). De esta forma
        podemos finalmente buscar por <code>churros AND chocolate</code>
EOT;
  $Lang['Helptext']['WWW']['part'][1]['Title']  = "Interfaz para guardar y editar";
  $Lang['Helptext']['WWW']['part'][1]['Text']   = <<<EOT
        &Eacute;sta interfaz le permite editar recetas guardadas o guardar nuevas
        recetas. Los n&uacute;meros deben usar &raquo;<code>.</code>&laquo; 
        (punto) como separador decimal.
        Las unidades deben ser unidades v&aacute;lidas de 
        <a href="units.php" target="units" onclick="units();">Mealmaster,
        RezKonv o alias definidos</a> y deben estar separadas de la
        cantidad por un espacio .
EOT;

  $Lang['Helptext']['WWW']['part'][2]['Title']  = "Algunos consejos sobre el uso de categor&iacute;s";
  $Lang['Helptext']['WWW']['part'][2]['Text']   = <<<EOT
	Las recetas se pueden incorporar en diferentes categorias. Realmente
	no hay un l&iacute;mite real para ello, sin embargo la especifaci&oacute;n del
	formato de mealmaster permite un m&aacute;ximo de cinco categor&iacute;s.
	Las nuevas categor&iacute;s se crean directamente, cada vez que una
	receta la usa por primara vez.
	Para mantener las categor&iacute;s en orden, es recomendable usar el
	siguiente esquema para las nuevas recetas, cuando se a&ntilde;ada nuevas recetas
	a la base de datos a trav&eacute;s del interfaz web:
	<ul>
	  <li>La primera categor&iacute;a debe describir el tipo de recetea. Por
	      ejemplo una "Sopa", un "Aperitivo" o un "Cocktail".</li>
	  <li>La segunda categor&iacute;a debe describir el origen de la receta.
	      Use el nombre del pa&iacute;s de origen como <code>Itaila</code>, 
	      <code>Francia</code> o <code>China</code>.</li>
	</ul>
EOT;

  $Lang['Helptext']['Feedback']['Title']	= "Sus comentarios";
  $Lang['Helptext']['Feedback']['Text'][0]	= <<<EOT
      Tenemos una lista de correo para usuarios y desarrolladores:
      <i>koch-suite-devel@lists.berlios.de</i>. &Eacute;sta lista de correo es
      p&uacute;blica, pero solamente las direcciones e-mail subscritas pueden
      escribir a la lista (para evitar spam). Por favor lea
      <a href="http://lists.berlios.de/mailman/listinfo/koch-suite-devel">&eacute;sta
      p&aacute;gina</a> para mayor informaci&oacute;n.
EOT;

  $Lang['pattern']['Source_ingr']	= "/(Fuente|Referencia)/i";
  $Lang['pattern']['Source']    = "(Fuente|Referencia)";
  $Lang['pattern']['Recorder']  = "(Introducida por)";
  $Lang['pattern']['Date']      = "(D&iacute;a|Introducida el)";

  $Lang['Locale']	= "es_ES.ISO8859-1";
?>
