# This file contains the substitution-rules for "sed"

# Space-separated list of all "raw" php-files.
KS_CONFIG=		koch-suite.inc
PHP_FILES_UNCONF=	functions.inc lang.inc output.inc \
			debug.inc defines.inc file.inc nocache.inc \
			auth.inc access_denied.inc loginform.inc pwcrypt.inc \
			accountlocked.inc setup.inc parser.inc
ADDITIONAL=		de.inc en.inc es.inc
SUBDIRS=		

CONF_FILE=		../config.sed

all: build
	@#${MAKE} subdir TRGT=all

build: ${PHP_FILES_UNCONF} ${KS_CONFIG}

${PHP_FILES_UNCONF}: ${PHP_FILES_UNCONF:%.inc=%.raw}
	sed -f ${CONF_FILE} ${@:%.inc=%.raw} > ${@}

${KS_CONFIG}: ${KS_CONFIG:%.inc=%.raw}
	sed -f ${CONF_FILE} ${@:%.inc=%.raw} > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$$i";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}";\
	done )

clean:
	@#${MAKE} subdir TRGT=clean
	rm -f ${PHP_FILES_UNCONF}
	rm -f ${KS_CONFIG}

distclean:

install: install-lib install-etc

install-lib: build
	( [ -d "${DESTDIR}/<%%PHP_LIBS%%>" ] || \
	<%%INSTALL%%> -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%PHP_LIBS%%> )
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${PHP_FILES_UNCONF} ${DESTDIR}/<%%PHP_LIBS%%>
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${ADDITIONAL} ${DESTDIR}/<%%PHP_LIBS%%>

install-etc: build
	( [ -d "${DESTDIR}/<%%ETC_PREFIX%%>" ] || \
	<%%INSTALL%%> -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%ETC_PREFIX%%> )
	-@(if [ -f "${DESTDIR}/<%%ETC_PREFIX%%>/${KS_CONFIG}" ] ; then \
	installed_conf=`grep '\$$Id.*$$' <%%ETC_PREFIX%%>/koch-suite.inc` ; \
	uninstalled_conf=`grep '\$$Id.*$$' ${KS_CONFIG}` ; \
	echo "*** ${DESTDIR}/<%%ETC_PREFIX%%>/${KS_CONFIG} exists. Leaving untouched."; \
	if [ "$${installed_conf}" != "$${uninstalled_conf}" ] ; then \
	echo "*** Configfiles have different versions. Please merge manually" ; \
	echo "*** Unified diff follows:" ; \
	diff -u <%%ETC_PREFIX%%>/koch-suite.inc ${KS_CONFIG} ; \
	exit 0; \
        fi ; \
	else \
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${KS_CONFIG} ${DESTDIR}/<%%ETC_PREFIX%%>; \
	fi )
