# This file contains the substitution-rules for "sed"

# Space-separated list of all "raw" php-files.
PHP_FILES_UNCONF=	config.inc functions.inc lang.inc output.inc
ADDITIONAL=		de.inc en.inc
SUBDIRS=		

CONF_FILE=		../config.sed

all: build
	@#${MAKE} subdir TRGT=all

build: ${PHP_FILES_UNCONF}

${PHP_FILES_UNCONF}: ${PHP_FILES_UNCONF:%.inc=%.raw}
	sed -f ${CONF_FILE} ${@:%.inc=%.raw} > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$$i";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}";\
	done )

clean:
	@#${MAKE} subdir TRGT=clean
	rm -f ${PHP_FILES_UNCONF}

distclean:

install: build
	( [ -d "${DESTDIR}/<%%PHP_LIBS%%>" ] || \
	install -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%PHP_LIBS%%> )
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${PHP_FILES_UNCONF} ${DESTDIR}/<%%PHP_LIBS%%>
	install -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${ADDITIONAL} ${DESTDIR}/<%%PHP_LIBS%%>
