# This file contains the substitution-rules for "sed"

# Space-separated list of all "raw" php-files.
KS_CONFIG=		koch-suite.inc
PHP_FILES_UNCONF=	functions.inc lang.inc output.inc \
			debug.inc defines.inc file.inc nocache.inc \
			auth.inc loginform.inc
ADDITIONAL=		de.inc en.inc 
SUBDIRS=		

CONF_FILE=		../config.sed

all: build
	@#${MAKE} subdir TRGT=all

build: ${PHP_FILES_UNCONF} ${KS_CONFIG}

${PHP_FILES_UNCONF}: ${PHP_FILES_UNCONF:%.inc=%.raw}
	sed -f ${CONF_FILE} ${@:%.inc=%.raw} > ${@}

${KS_CONFIG}: ${KS_CONFIG:%.inc=%.raw}
	sed -f ${CONF_FILE} ${@:%.inc=%.raw} > ${@}

subdir:
	@(for i in ${SUBDIRS} ; do\
	echo "====> ${THISDIR}/$$i";\
	cd $$i; \
	${MAKE} ${TRGT} THISDIR=${THISDIR}/$$i; \
	echo "<==== ${THISDIR}";\
	done )

clean:
	@#${MAKE} subdir TRGT=clean
	rm -f ${PHP_FILES_UNCONF}
	rm -f ${KS_CONFIG}

distclean:

install: install-lib install-etc

install-lib: build
	( [ -d "${DESTDIR}/<%%PHP_LIBS%%>" ] || \
	<%%INSTALL%%> -d -g <%%GROUP%%> -m 0755 -o <%%OWNER%%> ${DESTDIR}/<%%PHP_LIBS%%> )
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${PHP_FILES_UNCONF} ${DESTDIR}/<%%PHP_LIBS%%>
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${ADDITIONAL} ${DESTDIR}/<%%PHP_LIBS%%>

install-etc: build
	<%%INSTALL%%> -c -g <%%GROUP%%> -m 0644 -o <%%OWNER%%> ${KS_CONFIG} ${DESTDIR}/<%%ETC_PREFIX%%>
